name: Open Test Pull Request

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        name: setup git-user data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      -
        name: commit changes
        run: |
          git apply .github/demo-pr/changes.patch
          git commit -m 'fix: display correct times in the matches table'
          git push origin bug/matches-times
      -
        env:
          GH_TOKEN: GITHUB_TOKEN
        run: |
          gh pr create \
            --base main \
            --head bug/matches-times \
            --title 'Show local times for match dates' \
            --body-file .github/demo-pr/body.md \
            --label bug
